// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKP6zqH_5zxAWnEyl3fx7FRXJSqrY19Ko',
    appId: '1:1075675869886:web:e12e5d19a8de199987a4ef',
    messagingSenderId: '1075675869886',
    projectId: 'medvault-8a898',
    authDomain: 'medvault-8a898.firebaseapp.com',
    storageBucket: 'medvault-8a898.firebasestorage.app',
    measurementId: 'G-WJ89QJW0QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2EUr5WIfj18-jlz9g3XkD3fk_u6TqVDw',
    appId: '1:1075675869886:android:65d7976abf620f2887a4ef',
    messagingSenderId: '1075675869886',
    projectId: 'medvault-8a898',
    storageBucket: 'medvault-8a898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3WFl5oJWYBQjOBmMvF7gRZKKSGQrHY',
    appId: '1:1075675869886:ios:23813850f9347f1987a4ef',
    messagingSenderId: '1075675869886',
    projectId: 'medvault-8a898',
    storageBucket: 'medvault-8a898.firebasestorage.app',
    iosBundleId: 'com.example.medvault',
  );
}
